# Generated by Django 3.2 on 2021-05-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='texto_pregunta',
            field=models.CharField(max_length=210),
        ),
    ]
